name: CI-iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Build and test
      run: xcodebuild clean build -project EssentialFeed.xcodeproj -scheme "CI_iOS" CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13, OS=15.0" CODE_SIGNING_ALLOWED=NO
